// This file is auto generated by the Message Builder.
// Don't bother making changes to this file as they will be lost when recompiling.

// Message Builder by Claus Andersen.

using System;

using System.Reflection;

namespace RfSuit
{
	class MessageDispatcher
	{
		interface IMessageHandler
		{
			void Handle(Byte[] frame);
		}

		public delegate void MessageHandlerDelegate<T>(T message);
		
		class MessageHandler<T> : IMessageHandler where T : class
		{
			MessageHandlerDelegate<T> handler;
			ConstructorInfo constructor;

			public MessageHandler(MessageHandlerDelegate<T> handler)
			{
				this.handler = handler;
				constructor = typeof(T).GetConstructor(new Type[] { typeof(Byte[]) });
			}

			public void Handle(Byte[] frame)
			{
				var msg = constructor.Invoke(new object[] { frame }) as T;
				handler(msg);
			}
		}

		IMessageHandler[] handlers = new IMessageHandler[256];
	
		public delegate bool MessagePredicateDelegate(Byte destination, Byte source);
		public event MessagePredicateDelegate MessagePredicate;

		public void HandleFrame(byte[] frame)
		{
			Byte destination = frame[0];
			Byte source = frame[1];
			Byte messageId = frame[2];

			if (MessagePredicate == null || MessagePredicate(destination, source))
			{
				var handler = handlers[messageId];
				if (handler != null)
				{
					handler.Handle(frame);
				}
			}
		}

		public void AddHandler<T>(MessageHandlerDelegate<T> handler) where T : class
		{
			dynamic id = typeof(T).GetField("MessageId", BindingFlags.NonPublic | BindingFlags.Static).GetValue(null);

			handlers[id] = new MessageHandler<T>(handler);
		}
	}

	class NothingMessage
	{
		public Byte Destination;
		public Byte Source;
		static readonly Byte MessageId = 0;

		public NothingMessage()
		{ }

		public NothingMessage(Byte[] frame)
		{
			Destination = frame[0];
			Source = frame[1];
		}

		static public Byte[] Create(Byte destination, Byte source)
		{
			Byte[] buffer = new Byte[3];
			buffer[0] = destination;
			buffer[1] = source;
			buffer[2] = MessageId;
			return buffer;
		}

		public Byte[] Create()
		{
			return Create(Destination, Source);
		}
	}

	class SetTxPowerMessage
	{
		public Byte Destination;
		public Byte Source;
		static readonly Byte MessageId = 1;
		public Byte TxPower;

		public SetTxPowerMessage()
		{ }

		public SetTxPowerMessage(Byte[] frame)
		{
			Destination = frame[0];
			Source = frame[1];
			TxPower = frame[3];
		}

		static public Byte[] Create(Byte destination, Byte source, Byte txPower)
		{
			Byte[] buffer = new Byte[4];
			buffer[0] = destination;
			buffer[1] = source;
			buffer[2] = MessageId;
			buffer[3] = txPower;
			return buffer;
		}

		public Byte[] Create()
		{
			return Create(Destination, Source, TxPower);
		}
	}

	class EnableSweepingMessage
	{
		public Byte Destination;
		public Byte Source;
		static readonly Byte MessageId = 2;

		public EnableSweepingMessage()
		{ }

		public EnableSweepingMessage(Byte[] frame)
		{
			Destination = frame[0];
			Source = frame[1];
		}

		static public Byte[] Create(Byte destination, Byte source)
		{
			Byte[] buffer = new Byte[3];
			buffer[0] = destination;
			buffer[1] = source;
			buffer[2] = MessageId;
			return buffer;
		}

		public Byte[] Create()
		{
			return Create(Destination, Source);
		}
	}

	class DisableSweepingMessage
	{
		public Byte Destination;
		public Byte Source;
		static readonly Byte MessageId = 3;

		public DisableSweepingMessage()
		{ }

		public DisableSweepingMessage(Byte[] frame)
		{
			Destination = frame[0];
			Source = frame[1];
		}

		static public Byte[] Create(Byte destination, Byte source)
		{
			Byte[] buffer = new Byte[3];
			buffer[0] = destination;
			buffer[1] = source;
			buffer[2] = MessageId;
			return buffer;
		}

		public Byte[] Create()
		{
			return Create(Destination, Source);
		}
	}

	class ReportMessage
	{
		public Byte Destination;
		public Byte Source;
		static readonly Byte MessageId = 4;
		public Byte[] Rssis = new Byte[16];

		public ReportMessage()
		{ }

		public ReportMessage(Byte[] frame)
		{
			Destination = frame[0];
			Source = frame[1];
			Array.Copy(frame, 3, Rssis, 0, 16);
		}

		static public Byte[] Create(Byte destination, Byte source, Byte[] rssis)
		{
			Byte[] buffer = new Byte[19];
			buffer[0] = destination;
			buffer[1] = source;
			buffer[2] = MessageId;
			Array.Copy(rssis, 0, buffer, 3, 16);
			return buffer;
		}

		public Byte[] Create()
		{
			return Create(Destination, Source, Rssis);
		}
	}

}
