//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: log.proto
namespace dk.iha
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Entry")]
  public partial class Entry : global::ProtoBuf.IExtensible
  {
    public Entry() {}
    
    private byte[] _picture;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"picture", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] picture
    {
      get { return _picture; }
      set { _picture = value; }
    }
    private int _timestamp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
