// This file is auto generated by the Message Builder.
// Don't bother making changes to this file as they will be lost when recompiling.

// Message Builder by Claus Andersen.

#include <stdint.h>

enum
{
	MESSAGEID_SHOUT
};

typedef struct
{
	uint8_t source;
	uint8_t messageId;
} radioMsgMessageBase;

#define AsRadioMsgMessageBase(x) ((radioMsgMessageBase*)x)

typedef struct
{
	uint8_t source;
	uint8_t messageId;
} shoutMessage;

#define AsShoutMessage(x) ((shoutMessage*)x)
