/*
 * Diagnostics.h
 *
 *  Created on: 05/11/2010
 *      Author: Coma
 */

#ifndef DIAGNOSTICS_H_
#define DIAGNOSTICS_H_

#include "../Globals.h"

typedef enum
{
	// Kernel
	DIAGNOSTICS_SYSTEM_INITIALIZED,


	// Event dispatcher
	DIAGNOSTICS_COMPLETION_QUEUED,
	DIAGNOSTICS_COMPLETION_EXECUTED,
	DIAGNOSTICS_PROCESS_QUEUED,
	DIAGNOSTICS_PROCESS_EXECUTED,
	DIAGNOSTICS_PUBLISH_QUEUED,
	DIAGNOSTICS_PUBLISH_EXECUTED,
	DIAGNOSTICS_EVENT_QUEUE_OVERFLOW,
	DIAGNOSTICS_TOO_MANY_EVENT_SUBSCRIBERS,


	// Timer
	DIAGNOSTICS_TIMER_CREATED,
	DIAGNOSTICS_TIMER_STARTED,
	DIAGNOSTICS_TIMER_NOT_STARTED,
	DIAGNOSTICS_TIMER_RESTARTED,
	DIAGNOSTICS_TIMER_STOPPED,
	DIAGNOSTICS_TIMER_FIRED_AND_CONTINUED,
	DIAGNOSTICS_TIMER_FIRED_AND_STOPPED,


	// Memory subsystem
	DIAGNOSTICS_POOL_1_ALLOCATION,
	DIAGNOSTICS_POOL_1_RELEASE,
	DIAGNOSTICS_POOL_1_EXHAUSTED,
	DIAGNOSTICS_POOL_2_ALLOCATION,
	DIAGNOSTICS_POOL_2_RELEASE,
	DIAGNOSTICS_POOL_2_EXHAUSTED,
	DIAGNOSTICS_POOL_3_ALLOCATION,
	DIAGNOSTICS_POOL_3_RELEASE,
	DIAGNOSTICS_POOL_3_EXHAUSTED,
	DIAGNOSTICS_POOL_4_ALLOCATION,
	DIAGNOSTICS_POOL_4_RELEASE,
	DIAGNOSTICS_POOL_4_EXHAUSTED,
	DIAGNOSTICS_MEMORY_ALLOCATION_FAILED,
	DIAGNOSTICS_MEMORY_RELEASE_FAILED,


	// Network subsystem
	DIAGNOSTICS_RX_RTS,
	DIAGNOSTICS_RX_CTS,
	DIAGNOSTICS_RX_SENSOR_DATA,
	DIAGNOSTICS_RX_ACK,
	DIAGNOSTICS_TX_RTS,
	DIAGNOSTICS_TX_CTS,
	DIAGNOSTICS_TX_DATA,
	DIAGNOSTICS_TX_ACK,
	DIAGNOSTICS_DATA_QUEUED,
	DIAGNOSTICS_DATA_NOT_QUEUED,
	DIAGNOSTICS_NETWORK_TICK,
	DIAGNOSTICS_NETWORK_FORWARDING,


	// NEW
	DIAGNOSTICS_TIMER_TICK,
	// NEW ADC
	DIAGNOSTICS_ADC_CREATED,
	DIAGNOSTICS_ADC_CONVERSION_QUEUED,
	DIAGNOSTICS_ADC_FAILED_TO_QUEUE_CONVERSION,
	DIAGNOSTICS_ADC_CONVERSION_STARTED,
	DIAGNOSTICS_ADC_CONVERSION_COMPLETED,

	DIAGNOSTICS_NETWORK_FORWARDING_DROPPED,

	DIAGNOSTICS_POWER_MANAGER_RESOURCE_REQUEST_OVERFLOW,
	DIAGNOSTICS_POWER_MANAGER_RESOURCE_RELEASE_OVERFLOW,
	DIAGNOSTICS_NUMBER_OF_INTERNAL_EVENTS,

	DIAGNOSTICS_NETWORK_LINK_PACKET_QUEUED,
	DIAGNOSTICS_NETWORK_LINK_QUEUE_OVERRUN,

	DIAGNOSTICS_NETWORK_UNABLE_TO_CREATE_BED_PACKET,
	DIAGNOSTICS_NETWORK_UNABLE_TO_CREATE_RDD_PACKET,

	DIAGNOSTICS_NETWORK_CREATED_BED_PACKET,
	DIAGNOSTICS_NETWORK_CREATED_RDD_PACKET,

	DIAGNOSTICS_NETWORK_SENT_BED_PACKET,
	DIAGNOSTICS_NETWORK_SENT_RDD_PACKET,

	DIAGNOSTICS_NETWORK_JOINED,
	DIAGNOSTICS_NETWORK_CREATED_JOIN_REQUEST,
	DIAGNOSTICS_NETWORK_CREATED_JOIN_RESPONSE,
	DIAGNOSTICS_NETWORK_GOT_JOIN_REQUEST,
	DIAGNOSTICS_NETWORK_GOT_JOIN_RESPONSE,
	DIAGNOSTICS_NETWORK_STAR_TOPOLOGY_FALL_BACK,

	DIAGNOSTICS_MASTER_NODE_RUNNING,
	DIAGNOSTICS_SLAVE_NODE_RUNNING
} diagnostics_event;

extern void Diagnostics_Initialize();
extern void Diagnostics_SendRaw(uint8_t value);
extern void Diagnostics_SendEvent(uint8_t event);
extern void Diagnostics_SendMessage(uint8_t messageId, void* message, uint8_t messageLength);
extern void Diagnostics_SendState(uint8_t stateMachineId, uint8_t newState);

#endif /* DIAGNOSTICS_H_ */
