//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: log.proto
namespace dk.iha
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Entry")]
  public partial class Entry : global::ProtoBuf.IExtensible
  {
    public Entry() {}
    
    private double _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double timestamp
    {
      get { return _timestamp; }
      set { _timestamp = value; }
    }
    private readonly global::System.Collections.Generic.List<dk.iha.Picture> _pictures = new global::System.Collections.Generic.List<dk.iha.Picture>();
    [global::ProtoBuf.ProtoMember(2, Name=@"pictures", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dk.iha.Picture> pictures
    {
      get { return _pictures; }
    }
  
    private readonly global::System.Collections.Generic.List<dk.iha.LinkQualityIndicator> _results = new global::System.Collections.Generic.List<dk.iha.LinkQualityIndicator>();
    [global::ProtoBuf.ProtoMember(3, Name=@"results", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<dk.iha.LinkQualityIndicator> results
    {
      get { return _results; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LinkQualityIndicator")]
  public partial class LinkQualityIndicator : global::ProtoBuf.IExtensible
  {
    public LinkQualityIndicator() {}
    
    private int _EndPointA;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"EndPointA", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int EndPointA
    {
      get { return _EndPointA; }
      set { _EndPointA = value; }
    }
    private int _EndPointB;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"EndPointB", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int EndPointB
    {
      get { return _EndPointB; }
      set { _EndPointB = value; }
    }
    private double _Quality;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Quality
    {
      get { return _Quality; }
      set { _Quality = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Picture")]
  public partial class Picture : global::ProtoBuf.IExtensible
  {
    public Picture() {}
    
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
